import styles from "./index.module.css";
import Head from "next/head";
import { Map } from "@/components/map";
import { motion, useViewportScroll } from "framer-motion";
import { useEffect, useState } from "react";
import { FaArrowDown } from "react-icons/fa";

function Home() {
  const latLong = { lat: 51.5, lng: -0.1 } as google.maps.LatLngLiteral;

  const [hasScrolled, setHasScrolled] = useState(false);
  const { scrollY } = useViewportScroll();
  const [showArrow, setShowArrow] = useState(true);


  useEffect(() => {
    const handleScroll = () => {
      if (scrollY.get() > 0) {
        setHasScrolled(true);
        setShowArrow(false);
      } else {
        setHasScrolled(false);
        setShowArrow(true);
      }
    };

    scrollY.onChange(() => {
      handleScroll();
    });

    return () => window.removeEventListener('scroll', handleScroll);
  }, [scrollY]);

  const scrollToBottom = () => {
    window.scrollTo({
      top: document.documentElement.scrollHeight,
      behavior: "smooth",
    });
  };

  return (
    <>
      <Head>
        <title>SprintScape</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <motion.div className={styles.main}>
          <div className={[styles.container, styles.title].join(" ")}>
            <motion.h1
              initial={{ opacity: 0, x: -20 }}
              animate={{ opacity: hasScrolled ? 0 : 1, x: hasScrolled ? -20 : 0 }}
              transition={{ duration: 1 }}
            >
              Sprint <span className={styles.pinkSpan}>Scape</span> App
            </motion.h1>
          </div>
        </motion.div>
        <div className={styles.arrowContainer}
          onClick={scrollToBottom}
        >
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: showArrow ? 1 : 0, y: 0 }}
            transition={{ duration: 1 }}
          >
            <FaArrowDown className={styles.arrowIcon} />
          </motion.div>
        </div>
        <motion.div
          className={styles.mapContainer}
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: hasScrolled ? 1 : 0, y: hasScrolled ? 0 : 20 }}
          transition={{ duration: 1 }}
        >
          <Map center={latLong} zoom={5} />
        </motion.div>
      </div>
    </>
  );
}

export default Home;
