import styles from "./index.module.css";
import { type NextPage } from "next";
import Head from "next/head";

import { Map } from "@/components/map";

const Home: NextPage = () => {
  const latLong = { lat: 51.5, lng: -0.1 } as google.maps.LatLngLiteral;

  return (
    <>
      <Head>
        <title>SprintScape</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <h1 className={styles.title}>
            Sprint <span className={styles.pinkSpan}>Scape</span> App
          </h1>
          <Map center={latLong} zoom={5} />
        </div>
      </main>
    </>
  );
};

export default Home;
