import styles from "./index.module.css";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "@/utils/api";
import { useUser } from "@clerk/nextjs";

const Home: NextPage = () => {
  const user = useUser();
  const { data } = api.organisation.getAll.useQuery();

  return (
    <>
      <Head>
        <title>SprintScape</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <h1 className={styles.title}>
            Sprint <span className={styles.pinkSpan}>Scape</span> App
          </h1>
          <p className={styles.showcaseText}>
            {data?.map((item) => item.name).join(", ")}

          </p>
        </div>
      </main>
    </>
  );
};

export default Home;
